version: '3.8'

services:
  db:
    image: mysql:8.0.33
    container_name: pixel-db
    restart: "always"
    environment:
      MYSQL_DATABASE: Pixel_Paradise
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - pixel-network

  app:
    image: przx27/backend-app:java21
    container_name: pixel-app
    ports:
      - "443:8443"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/Pixel_Paradise
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    restart: "always"
    networks:
      - pixel-network

volumes:
  db_data:

networks:
  pixel-network:
